### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by andygoeroeg** [InteractiveNinja/M183#3]
Funktionen, welche nur bestimmte
Benutzer / Benutzergruppen ausführen
dürfen, sind sowohl im Frontend wie
auch im Backend berücksichtigt und
funktionieren

**Comment by InteractiveNinja** [comment]
Admin Rest Routes werden nicht geschützt. Sobald der User eingeloggt ist und eine makeshift "session" besitzt, kann dieser die Admin Routes aufrufen.

**Comment by InteractiveNinja** [comment]
Ich empfehle Analog zum `checkError` eine Middleware für die Prüfung des Admin Flag zu erstellen
