### ISSUE TITLE
Login & Password Security

### ISSUE THREAD

**Issue by andygoeroeg** [InteractiveNinja/M183#5]
Der Login-Mechanismus ist sicher
implementiert, Passwörter sind
gehashed und gesalzen gespeichert

**Comment by InteractiveNinja** [comment]
Hashing wird im `user.ts` Model beim Speichervorgang des Benutzers  getätigt.
Die überschriebene Methode `User#save 19:3` verwendet [bcryptjs](https://www.npmjs.com/package/bcryptjs)

**Comment by andygoeroeg** [comment]
Implementiert und dokumentiert
