### ISSUE TITLE
Absicherung Standardangriffe

### ISSUE THREAD

**Issue by InteractiveNinja** [InteractiveNinja/M183#7]
Absicherung gegen XSS und Injections

**Comment by InteractiveNinja** [comment]
[Angular Security](https://angular.io/guide/security)

**Comment by andygoeroeg** [comment]
Macht es Sinn Helmet's XSS Module rein zu schmeissen?

**Comment by InteractiveNinja** [comment]
> Macht es Sinn Helmet's XSS Module rein zu schmeissen?

Hmm, eigentlich wäre ich der Meinung aus https://github.com/InteractiveNinja/M183/pull/39#discussion_r1061547450, da aber anscheinend der XSS Buggy scheint könnte man das machen, lässt sich sicher auch gut Dokumentieren.

**Comment by InteractiveNinja** [comment]
In  #41 wurde zusätzlich Helmets htst Module geadded
